[project]
name = 'Decentralized-Energy-Grid-Balancing'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.generation-scheduling]
path = 'contracts/generation-scheduling.clar'
clarity_version = 2
epoch = 2.5

[contracts.load-forecasting]
path = 'contracts/load-forecasting.clar'
clarity_version = 2
epoch = 2.5

[contracts.settlement]
path = 'contracts/settlement.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
